### ISSUE TITLE
Unable to install FME server on kubernetes

### ISSUE THREAD

**Issue by hnpatadia** [safesoftware/helm-charts#78] opened 2022-05-17 06:48 UTC
Hi all,

I am using helm-charts for installing latest 2022 releast. 

Steps:

1. Add repo
`helm repo add safesoftware https://safesoftware.github.io/helm-charts/`

2. Update repo
`helm repo update`

4. Get values.yaml
`helm show values safesoftware/fmeserver-2022.0 >> values2022.yaml`

6. Install
`helm install fme2022 safesoftware/fmeserver-2022.0 -f values2022.yaml -n fmeserver2022`

**Issue:**
When applied I see a message: 

`Error: template: fmeserver-2022.0/charts/postgresql/templates/svc.yaml:34:24: executing "fmeserver-2022.0/charts/postgresql/templates/svc.yaml" at <{{template "postgresql.port" .}}>: template "postgresql.port" not defined`

**Comment by agxs** [comment] 2022-06-03 14:36
I get a similar issue with the 2022.0 version, (although its a different value):

```
Error: INSTALLATION FAILED: template: fmeserver-2022.0/charts/postgresql/templates/svc.yaml:1:79: executing "fmeserver-2022.0/charts/postgresql/templates/svc.yaml" at <.Values.service.annotations>: nil pointer evaluating interface {}.annotations
```

The 2021.2 chart works fine though.

The options I'm overriding are:

```
helm install fmeserver safesoftware/fmeserver-2022.0 --set fmeserver.image.tag=22343 --set deployment.hostname=<hostname> --set deployment.port=80 --set deployment.disableTLS=true
```

(TLS is disabled because this is just testing on a temporary dev cluster)

**Comment by garnold54** [comment] 2022-06-04 00:52
This should now be fixed. We had an issue when upgrading our postgres chart and the process we use to release it publicly.

If you do `helm repo update` and deploy again it should be fixed.

**Closed by garnold54** 2022-06-04 00:52 UTC

**Comment by agxs** [comment] 2022-06-06 08:34
Thanks for the quick response. Confirmed working.
